name: Test it

on:
  workflow_dispatch:
  push:
    branches:
      - branch-1
jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sample -1 '
        run : echo "Hi"
      - name: Delete the forked repository if exists
        uses: actions/github-script@v5
        with:
          script: |
            const repo = "source-1"
            const owner = "vineeth-asml"

            #GET repo 
            const repoInfo = await github.rest.repos.get({
              owner,
              repo,
            });
            
            
            //console.log(`repoInfo ${repoInfo}`)
            //console.log(`repoInfo.Id ${repoInfo.Id}`)
            // Delete repo
            //if( repoInfo.Id ) {
            //  await github.rest.repos.delete({
            //    owner,
            //    repo,
            //  });
            // }           
