on:
  push: 
#    branches: 
#      - branch-1


name: Send notification 
jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v3
    - name: Get Name of the SPOC
      id: get_spoc_name
      run: |
        pushd config
        while IFS=, read -r date name
        do
          today=$(date +%F)
          echo $today
          echo $date
          echo $name
          if[ "${today}"=="${date}" ];then
            echo "$name is the spoc for this week"
          fi
        done < spoc.csv
