on:
  push: 
    branches: 
      - branch-1

  workflow_dispatch:

env:
  FILE_SIZE_TO_SEARCH: 15000 #in Bytes 

name: Get files with larger size    
jobs:
  get-large-files:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/github-script@v5
      name: Search for the file
      env:
        MAX_FILE_SIZE: ${{ env.FILE_SIZE_TO_SEARCH }}
      with:
        script: |
          const org = 'actions'
          const {MAX_FILE_SIZE} = process.env
          const q = `size:>${MAX_FILE_SIZE}+org:${org}`

          const searchResult = await github.rest.search.code({
            q,
          });
          
          const responseString = JSON.stringify(searchResult)
          core.info(`searchOutput :  ${responseString}`)
          let resultsRows;

          const resultsHeader = [
            {data: 'File', header: true},
            {data: 'Path', header: true},
            {data: 'Repository', header: true},
            {data: 'URL', header: true}
          ]

          summaryBody = `| File | Path | Repository | URL \n|---	|---	|---	|---	|---	|\n`
          for (const item of searchResult.data.items) {
            const fileName = `${item.name}`
            const filePath = `${item.path}`
            const repository = `${item.repository.full_name}`,
            const url = `${item.url}`
            summaryBody += `|${fileName} | ${filePath} | ${repository} | ${url}`
            
          }
          
          core.info('Markdown : ${summaryBody}')

          await core.summary
            .addHeading(':eyes: Search Results :eyes:')
            .addRaw(summaryBody)
            .write()
          
