name: Test it

on:
  workflow_dispatch:
  push:
    branches:
      - branch-1
jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sample -1 '
        run : echo "Hi"
      - name: Check if repository exists
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.VINEETH_PAT_TOKEN }}
          script: |
          
            try { 
            const repo = "source-1"
            const owner = "vineeth-asml"

            // GET repo 
            const repoInfo = await github.rest.repos.get({
              owner,
              repo,
            });
            
            console.log(`Repository ${owner}/${repo} is not found. Delete before proceeding`)
            
            await github.rest.repos.delete({
                owner,
                repo,
            });
            
            } catch {
              console.log(`Repository ${owner}/${repo} is not found`)
            }
      - name: Check if repository exists
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.VINEETH_PAT_TOKEN }}
          script: |
          
            try { 
            const repo = "source-133"
            const owner = "vineeth-asml"

            // GET repo 
            const repoInfo = await github.rest.repos.get({
              owner,
              repo,
            });
            
            console.log(`Repository ${owner}/${repo} is not found. Delete before proceeding`)
            
            await github.rest.repos.delete({
                owner,
                repo,
            });
            
            } catch {
              console.log(`Repository ${owner}/${repo} is not found`)
            }            
