name: Test it

on:
  workflow_dispatch:
  push:
    branches:
      - branch-1
env:
  RUN_URL : "${{ github.GITHUB_SERVER_URL}}/${{ github.GITHUB_REPOSITORY}}/actions/runs/${{github.GITHUB_RUN_ID }}"
  GIT_COMMIT_ID: ${{ github.GITHUB_SHA }}
jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sample -1 '
        run : |
          echo "Hi URL is $RUN_URL"
          echo "Hi GITHUB_SHA is $GIT_COMMIT_ID"
      - name: Check if repository exists
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.VINEETH_PAT_TOKEN }}
          script: |
            const repo = "source-1"
            const owner = "vineeth-asml"
            let repoExist = false
            try { 

            // GET repo 
            const repoInfo = await github.rest.repos.get({
              owner,
              repo,
            });
            
            repoExist = true
            console.log(`Repository ${owner}/${repo} exists already. Delete before proceeding`)
            
            await github.rest.repos.delete({
                owner,
                repo,
            });
            console.log(`Successfully Deleted of Repository ${owner}/${repo}`)
            } catch {
              if(!repoExist) {
                console.log(`Repository ${owner}/${repo} is not found`)
              } else {
                console.log(`Deletion of Repository ${owner}/${repo} failed`)
              }
            }
      - name: Check if repository exists
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.VINEETH_PAT_TOKEN }}
          script: |
            const repo = "source-122"
            const owner = "vineeth-asml"
            let repoExist = false
            try { 
            // GET repo 
            const repoInfo = await github.rest.repos.get({
              owner,
              repo,
            });
            
            repoExist = true
            console.log(`Repository ${owner}/${repo} exists already. Delete before proceeding`)
            
            await github.rest.repos.delete({
                owner,
                repo,
            });
            
            } catch {
              if(!repoExist) {
                console.log(`Repository ${owner}/${repo} is not found`)
              } else {
                console.log(`Deletion of Repository ${owner}/${repo} failed`)
              }
            }         
