name: Test it

on:
  workflow_dispatch:
  push:
    branches:
      - branch-1
jobs:
  test-job-1:
    runs-on: ubuntu-latest
    if : 1==2
    steps:
      - name: 'Sample -1 '
        run : echo "Hi"

  test-job-2:
    runs-on: ubuntu-latest  
    needs:
      - test-job-1
    steps:
      - name: 'Sample -1 '
        run : echo "Hi"      
